# -*- coding: utf-8 -*-
"""jpgTOhex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-cBGUvGFqhT2U1bp5vt82v9lKwvS3Yr
"""

from PIL import Image

def rgb_to_hex_mask(rgb):
    # Extract RGB components
    red, green, blue = rgb

    # Convert RGB to hexadecimal format and combine them into a single string
    hex_mask = f"0x{blue:02X}{green:02X}{red:02X}"  # Use f-string formatting

    return hex_mask

img = Image.open("/content/drive/MyDrive/Colab Notebooks/SFU.jpg")

img.show()

pix_val = list(img.getdata())

hex_mask = []
for i in range(len(pix_val)):
    hex_mask.append(rgb_to_hex_mask(pix_val[i]))

print(hex_mask)



from google.colab import drive
drive.mount('/content/drive')